---

- name: Install python-software-properties
  apt: name=python-software-properties state=present

- name: Update repositories
  apt_repository: repo={{ java_repo }} state=present update_cache=yes

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-8-oracle

- name: Install Java 8
  apt: name=oracle-java8-installer state=present

- name: Download Graylog repository package
  get_url: url={{ graylog_packages_url }} dest=/tmp/graylog_repository.deb

- apt: name=apt-transport-https state=installed

- name: Install Graylog repository
  apt: deb=/tmp/graylog_repository.deb state=installed dpkg_options='force-all'
  register: install_repo

- apt: update_cache=yes
  when: install_repo.changed == True
