---
- name: Install Java 1.7
  apt: name=openjdk-7-jre-headless state=present

- name: Download Graylog2 repository package
  get_url: url=http://packages.graylog2.org/repo/packages/graylog2-0.20-repository-ubuntu14.04_latest.deb dest=/tmp/graylog2_repository.deb

- name: Install Graylog2 repository
  apt: deb=/tmp/graylog2_repository.deb state=installed

- name: Install Graylog2 web UI
  apt: name=graylog2-web state=present update_cache=yes

- name: Configure Graylog2 web
  template: src=graylog2.web.conf.j2 dest=/etc/graylog2/web/graylog2-web-interface.conf owner=graylog2 group=graylog2 mode=0644
  notify: restart graylog2-web

- name: Configure Graylog2 web defaults
  template: src=graylog2.web.default.j2 dest=/etc/default/graylog2-web owner=graylog2 group=graylog2 mode=0644
  notify: restart graylog2-web
